on:
  push:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 29]
        node-version: [14.x, 18.x]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Install dependencies
        run: npm install
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: '${{ matrix.api-level }}'
          profile: 3.2" QVGA (ADP2)
          disable-animations: true
          target: google_apis
          script: npm run build && npm test
  deploy:
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'      
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}